# Generated by Django 3.2.5 on 2021-10-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=20),
        ),
    ]
