# Generated by Django 3.2.5 on 2021-10-27 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='full-stack-developer.png', upload_to='blog_pictures/'),
        ),
    ]
