# Generated by Django 3.2.5 on 2021-10-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211027_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='full-stack-developer.png', upload_to='blog_pictures/'),
        ),
    ]
