# Generated by Django 3.2.8 on 2021-10-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211027_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Full-Stack', 'Full-Stack'), ('Front-end', 'Front-end'), ('Back-end', 'Back-end')], default='Full-Stack', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Publish', 'Publish')], default='Draft', max_length=10),
        ),
    ]
